routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\GuestController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', function () {
    return view('guest/guest');
});
Route::get('/guest/listproduk', [GuestController::class, 'index']);

Route::group(['middleware' =>['auth', 'cekRole:admin,user']],function(){
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('kategori', KategoriController::class);
    Route::resource('transaksi', TransaksiController::class);
    Route::resource('barang', BarangController::class);
    
});

Route::group(['middleware' =>['auth', 'cekRole:user']],function(){
    Route::get('/cart-index',[CartController::class, 'index']);
    Route::post('cart/{id}', [CartController::class, 'tambahCart']);
    Route::delete('cart-delete/{id}', [CartController::class, 'deleteCart']);
    Route::get('check-out',[CartController::class, 'checkOut']);
    Route::post('add-address', [CartController::class, 'addAdress']);
    Route::get('edit-address/{id}', [CartController::class, 'editAddress']);
    Route::get('delete-address/{id}', [CartController::class, 'deleteAddress'])->name("deleteAddress");
    Route::post('store-edit-address/{id}', [CartController::class, 'storeEditAddress']);
    Route::post('store-payment/{id}', [CartController::class, 'storePayment']);
    Route::get('/riwayat-transaksi', [CartController::class, 'indexTransaction']);
    Route::get('/cetak-transaksi/{id}', [CartController::class, 'prinTransaction']);
});

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;
    protected $table='kategoris'; 
    protected $guarded = ['id'];

    protected $fillable =[
        'nama_kategori'
    ];

    public function barang(){
        return $this->hasMany(Barang::class); 
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kategori;
use Illuminate\Support\Facades\DB;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data_kategori = Kategori::all();

        return view('dashboard/admin/kategori/kategori_index', ['data_kategori' => $data_kategori]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data_kategori_create = Kategori::all();
        return view('dashboard/admin/kategori/kategori_create', ['data_kategori_create' => $data_kategori_create]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_kategori' => 'required',
        ]);

        $data_kategori_store = new Kategori;
        $data_kategori_store->nama_kategori = $request->get('nama_kategori');

        $data_kategori_store->save();

        return redirect()->route('kategori.index')
            ->with('success', 'Kategori Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data_kategori_show = Kategori::where('id', $id)->first();
        return view('dashboard/admin/kategori/kategori_show', ['data_kategori_show' => $data_kategori_show]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data_kategori_edit = Kategori::where('id', $id)->first();
        return view('dashboard/admin/kategori/kategori_edit', ['data_kategori_edit' => $data_kategori_edit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_kategori' => 'required',
        ]);

        $data_kategori_update = Kategori::where('id', $id)->first();
        $data_kategori_update->nama_kategori = $request->get('nama_kategori');

        $data_kategori_update->save();

        return redirect()->route('kategori.index')
        ->with('success', 'Kategori Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kategori::where('id', $id)->delete();
        return redirect()->route('kategori.index')
            -> with('success', 'Kategori Berhasil Dihapus');
    }
}

resources/views/dashboard/admin/kategori/kategori_create.blade.php
@extends('dashboard.main')

@section('title', 'Kategori')


@section('content')
<div class="container mt-5">
 
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Tambah Kategori
        </div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{ route('kategori.store') }}" id="myForm" enctype="multipart/form-data">
        @csrf
            <div class="form-group">
                <label for="nama_kategori">Nama Kategori</label> 
                <input type="text" name="nama_kategori" class="form-control" id="nama_kategori" aria-describedby="Nim" > 
            </div>
            <br><br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </div>
    </div>
 </div>
 </div>
@endsection

resources/views/dashboard/admin/kategori/kategori_edit.blade.php
@extends('dashboard.main')

@section('title', 'Kategori')


@section('content')
<div class="container mt-5">
 
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Edit Kategori
        </div>
        <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="post" action="{{ route('kategori.update', $data_kategori_edit->id) }}" id="myForm" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="nama_kategori">Nama Kategori</label>
        <br> 
        <input type="text" name="nama_kategori" class="form-control" id="nama_kategori" value="{{ $data_kategori_edit->nama_kategori }}" aria-describedby="nama_kategori" > 
    </div>
    <br><br>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
    </div>
    </div>
</div>

@endsection

resources/views/dashboard/admin/kategori/kategori_index.blade.php
@extends('dashboard.main')

@section('title', 'Kategori')


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Kategori</h2>
    </div>
    
    <div class="float-right my-2 ">
        <a class="btn btn-success" href="{{ route('kategori.create') }}"> Input Kategori</a>
    </div>
    <table class="table table-bordered" style="width: 500px">
            <tr>
                <th width = "100px">Nama Kategori</th>
    
                <th width = "300px">Action</th>
            </tr>
            @foreach ($data_kategori as $ktgr)
            <tr>
                <td>{{ $ktgr ->nama_kategori }}</td>
    
                <td>
                <form action="{{ route('kategori.destroy',['kategori'=>$ktgr->id]) }}" method="POST">
                    
                    <a class="btn btn-info" href="{{ route('kategori.show',$ktgr->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('kategori.edit',$ktgr->id) }}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
                </td>
            </tr>
            @endforeach
    </table>

@endsection

resources/views/dashboard/admin/kategori/kategori_show.blade.php
@extends('dashboard.main')

@section('title', 'Kategori')


@section('content')
<div class="container mt-5">
 
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Detail Kategori
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>Nama Kategori: </b>{{$data_kategori_show->nama_kategori}}</li>
                </ul>
            </div><br>
            <a class="btn btn-success mt-3" href="{{ route('kategori.index') }}">Kembali</a>
        </div>
    </div>
 </div>

@endsection