routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\GuestController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', function () {
    return view('guest/guest');
});
Route::get('/guest/listproduk', [GuestController::class, 'index']);

Route::group(['middleware' =>['auth', 'cekRole:admin,user']],function(){
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('kategori', KategoriController::class);
    Route::resource('transaksi', TransaksiController::class);
    Route::resource('barang', BarangController::class);
    
});

Route::group(['middleware' =>['auth', 'cekRole:user']],function(){
    Route::get('/cart-index',[CartController::class, 'index']);
    Route::post('cart/{id}', [CartController::class, 'tambahCart']);
    Route::delete('cart-delete/{id}', [CartController::class, 'deleteCart']);
    Route::get('check-out',[CartController::class, 'checkOut']);
    Route::post('add-address', [CartController::class, 'addAdress']);
    Route::get('edit-address/{id}', [CartController::class, 'editAddress']);
    Route::get('delete-address/{id}', [CartController::class, 'deleteAddress'])->name("deleteAddress");
    Route::post('store-edit-address/{id}', [CartController::class, 'storeEditAddress']);
    Route::post('store-payment/{id}', [CartController::class, 'storePayment']);
    Route::get('/riwayat-transaksi', [CartController::class, 'indexTransaction']);
    Route::get('/cetak-transaksi/{id}', [CartController::class, 'prinTransaction']);
});

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    use HasFactory;

    protected $guarded = ['id'];
    protected $table='barang'; 

    protected $fillable =[
        'nama',
        'kategori_id',
        'harga',
        'stok',
        'deskripsi',
        'gambar',
    ];

    public function kategori(){
        return $this->belongsTo(Kategori::class, 'kategori_id');
    }

    public function cart_details(){
        return $this->hasMany(Cart_Details::class, 'cart_id');
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use App\Models\Barang;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data_barang = Barang::with('kategori')->get();
        if (auth()->user()->role=='user') {
            return view('/dashboard/user/listproduk', ['data_barang' => $data_barang]);
        } else {
            return view('/dashboard/admin/barang/barang_index', ['data_barang' => $data_barang]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data_barang_create = Kategori::all();
        return view('/dashboard/admin/barang/barang_create', ['data_barang_create' => $data_barang_create]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'harga' => 'required',
            'stok' => 'required',
            'deskripsi' => 'required',
            'foto'=> 'required',
        ]);

        if ($request->file('foto')) {
            $image_name = $request->file('foto')->store('images', 'public');
        }

        $data_barang_store = new Barang;
        $data_barang_store->nama = $request->get('nama');
        $data_barang_store->harga = $request->get('harga');
        $data_barang_store->stok = $request->get('stok');
        $data_barang_store->deskripsi = $request->get('deskripsi');
        $data_barang_store->gambar = $image_name;

        $data_kategori = new Kategori;
        $data_kategori->id = $request->get('kategori');

        $data_barang_store->kategori()->associate($data_kategori);
        $data_barang_store->save();

        return redirect()->route('barang.index')
        ->with('success', 'Barang Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data_barang_show = Barang::with('kategori')->where('id', $id)->first();
        return view('/dashboard/admin/barang/barang_show', ['data_barang_show' => $data_barang_show]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data_barang_edit = Barang::with('kategori')->where('id', $id)->first();
        $kategori = Kategori::all();
        return view('/dashboard/admin/barang/barang_edit', compact('data_barang_edit', 'kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'harga' => 'required',
            'stok' => 'required',
            'deskripsi' => 'required',
            'foto'=>'required',
        ]);

        $data_barang_update = Barang::with('kategori')->where('id', $id)->first();
        $data_barang_update->nama = $request->get('nama');
        $data_barang_update->harga = $request->get('harga');
        $data_barang_update->stok = $request->get('stok');
        $data_barang_update->deskripsi = $request->get('deskripsi');
        if($data_barang_update->gambar && file_exists(storage_path('./app/public/'. $data_barang_update->gambar))){
            Storage::delete(['./public/',  $data_barang_update->gambar]);
        }
        $image_name = $request->file('foto')->store('image', 'public');
        $data_barang_update->gambar = $image_name;

        $kategori = new Kategori();
        $kategori->id = $request->get('kategori');
        
        $data_barang_update->kategori()->associate($kategori);
        $data_barang_update->save();
        
        return redirect()->route('barang.index')
            ->with('success', 'Barang Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Barang::where('id', $id)->delete();
        return redirect()->route('barang.index')
            -> with('success', 'Mahasiswa Berhasil Dihapus');
    }
}

resources/views/dashboard/admin/barang/barang_create.blade.php
@extends('dashboard.main')

@section('title', 'Barang')


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Barang</h2>
    </div>
    
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Tambah Barang
        </div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{ route('barang.store') }}" id="myForm" enctype="multipart/form-data">
        @csrf
            <div class="form-group">
                <label for="nama">Nama Barang</label> 
                <input type="text" name="nama" class="form-control" id="nama" aria-describedby="nama" > 
            </div>
            <div class="form-group">
                <label for="kategori">Nama Kategori</label> 
                <select class="form-control" name="kategori">
                @foreach($data_barang_create as $ktgr)
                    <option value="{{$ktgr->id}}">{{$ktgr->nama_kategori}}</option>
                @endforeach
                </select>
            </div>
            <div class="form-group">
                <label for="harga">Harga</label> 
                <input type="harga" name="harga" class="form-control" id="harga" aria-describedby="harga" > 
            </div>
            <div class="form-group">
                <label for="stok">Stok</label> 
                <input type="stok" name="stok" class="form-control" id="stok" aria-describedby="stok" > 
            </div>
            <div class="form-group">
                <label for="deskripsi">Deskripsi</label> 
                <input type="deskripsi" name="deskripsi" class="form-control" id="deskripsi" aria-describedby="deskripsi" > 
            </div>
            <div class="form-group">
                <label for="foto">Foto</label> 
                <input type="file" name="foto" class="form-control" id="foto" aria-describedby="foto" > 
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </div>
    </div>
 </div>
@endsection

resources/views/dashboard/admin/barang/barang_edit.blade.php
@extends('dashboard.main')

@section('title', 'Barang')


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Barang</h2>
    </div>
    
    <div class="container mt-5">
 
        <div class="row justify-content-center align-items-center">
            <div class="card" style="width: 24rem;">
                <div class="card-header">
                Edit Barang
            </div>
            <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{ route('barang.update', $data_barang_edit->id) }}" id="myForm" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="nama">Nama Barang</label> 
            <input type="text" name="nama" class="form-control" id="nama" value="{{ $data_barang_edit->nama }}" aria-describedby="nama" > 
        </div>
        <div class="form-group">
            <label for="kategori">Nama Kategori</label>
            <select class="form-control" name="kategori">
            @foreach($kategori as $ktgr)
                <option value="{{$ktgr->id}}" {{ $data_barang_edit->kategori_id == $ktgr->id ? 'selected' : ''}}>{{$ktgr->nama_kategori}}</option>
            @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="harga">Harga</label> 
            <input type="text" name="harga" class="form-control" id="harga" value="{{ $data_barang_edit->harga }}" aria-describedby="harga" > 
        </div>
        <div class="form-group">
            <label for="stok">Stok</label> 
            <input type="stok" name="stok" class="form-control" id="stok" value="{{ $data_barang_edit->stok }}" aria-describedby="stok" > 
        </div>
        <div class="form-group">
            <label for="deskripsi">Deskripsi</label> 
            <input type="deskripsi" name="deskripsi" class="form-control" id="deskripsi" value="{{ $data_barang_edit->stok }}" aria-describedby="deskripsi" > 
        </div>
        <div class="form-group"> 
            <label for="foto">Foto</label> 
            <input type="file" class="form-control" name="foto" id="foto" value="{{$data_barang_edit->gambar}}"></br> 
                <img width="250px" src="{{asset('storage/'.$data_barang_edit->gambar)}}"> 
        </div> 
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </div>
        </div>
        </div>
    </div>

@endsection

resources/views/dashboard/admin/barang/barang_index.blade.php
@extends('dashboard.main')

@section('title', 'Barang')


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Barang</h2>
    </div>
    
    <div class="float-right my-2">
        <a class="btn btn-success" href="{{ route('barang.create') }}"> Input Barang</a>
    </div>
    <table class="table table-bordered">
        <tr>
            <th>Nama Barang</th>
            <th>Nama Kategori</th>
            <th>Harga</th>
            <th>Stok</th>
            <th>Deskripsi</th>
            <th>Foto</th>

            <th width="300px">Action</th>
        </tr>
        @foreach ($data_barang as $brng)
        <tr>
 
            <td>{{ $brng ->nama }}</td>
            <td>{{ $brng ->kategori ->nama_kategori }}</td>
            <td>{{ $brng ->harga }}</td>
            <td>{{ $brng ->stok }}</td>
            <td>{{ $brng ->deskripsi }}</td>
            <td><img width="125px"
                src="{{asset('storage/'.$brng->gambar)}}"></td> 
            <td>
            <form action="{{ route('barang.destroy',['barang'=>$brng->id]) }}" method="POST">
                
                <a class="btn btn-info" href="{{ route('barang.show',$brng->id) }}">Show</a>
                <a class="btn btn-primary" href="{{ route('barang.edit',$brng->id) }}">Edit</a>
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            </td>
        </tr>
        @endforeach
    </table>
@endsection

resources/views/dashboard/admin/barang/barang_show.blade.php
@extends('dashboard.main')

@section('title', 'Barang')


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Barang</h2>
    </div>
    
    <div class="container mt-5">
 
        <div class="row justify-content-center align-items-center">
            <div class="card" style="width: 24rem;">
                <div class="card-header">
                Detail Barang
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b>Nama Barang  : </b>{{$data_barang_show->nama}}</li>
                        <li class="list-group-item"><b>Nama Kategori: </b>{{$data_barang_show->kategori->nama_kategori}}</li>
                        <li class="list-group-item"><b>Harga        : </b>{{$data_barang_show->harga}}</li>
                        <li class="list-group-item"><b>Stok         : </b>{{$data_barang_show->stok}}</li>
                        <li class="list-group-item"><b>Deskripsi    : </b>{{$data_barang_show->deskripsi}}</li>
                        <li class="list-group-item"> <img width="150px" src="{{asset('storage/'.$data_barang_show->gambar)}}"></li>
                    </ul>
                </div><br>
                <a class="btn btn-success mt-3" href="{{ route('barang.index') }}">Kembali</a>
            </div>
        </div>
     </div>

@endsection