routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\GuestController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


Route::get('/', function () {
    return view('guest/guest');
});
Route::get('/guest/listproduk', [GuestController::class, 'index']);

Route::group(['middleware' =>['auth', 'cekRole:admin,user']],function(){
    Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('dashboard');
    Route::resource('kategori', KategoriController::class);
    Route::resource('transaksi', TransaksiController::class);
    Route::resource('barang', BarangController::class);
    
});

Route::group(['middleware' =>['auth', 'cekRole:user']],function(){
    Route::get('/cart-index',[CartController::class, 'index']);
    Route::post('cart/{id}', [CartController::class, 'tambahCart']);
    Route::delete('cart-delete/{id}', [CartController::class, 'deleteCart']);
    Route::get('check-out',[CartController::class, 'checkOut']);
    Route::post('add-address', [CartController::class, 'addAdress']);
    Route::get('edit-address/{id}', [CartController::class, 'editAddress']);
    Route::get('delete-address/{id}', [CartController::class, 'deleteAddress'])->name("deleteAddress");
    Route::post('store-edit-address/{id}', [CartController::class, 'storeEditAddress']);
    Route::post('store-payment/{id}', [CartController::class, 'storePayment']);
    Route::get('/riwayat-transaksi', [CartController::class, 'indexTransaction']);
    Route::get('/cetak-transaksi/{id}', [CartController::class, 'prinTransaction']);
});

app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    use HasFactory;

    public function cart(){
        return $this->belongsTo(Cart::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function alamat(){
        return $this->belongsTo(AlamatPengiriman::class);
    }
}

resources/views/dashboard/admin/payment/cetak.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Transaction Report</title>

    <style>
        .invoice-box {
            width: 100%;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
        }

        .invoice-box table {
            width: 100%;
            line-height: inherit;
            text-align: left;
        }

        .invoice-box table td {
            padding: 5px;
            vertical-align: top;
        }

        /* .invoice-box table tr td:nth-child(2) {
            text-align: right;
        } */

        .invoice-box table tr.top table td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.top table td.title {
            color: #333;
        }

        .invoice-box table tr.information table td {
            padding-bottom: 40px;
        }

        .invoice {
            background: #eee;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
        }

        .invoice-box table tr.heading td {
            background: #B8860B;
            color: white;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
        }

        .invoice-box table tr.details td {
            padding-bottom: 20px;
        }

        .invoice-box table tr.item td {
            border-bottom: 1px solid #eee;
        }

        .invoice-box table tr.item.last td {
            border-bottom: none;
        }

        .invoice-box table tr.total td:nth-child(2) {
            border-top: 2px solid #eee;
            font-weight: bold;
        }

        @media only screen and (max-width: 600px) {
            .invoice-box table tr.top table td {
                width: 100%;
                display: block;
                text-align: center;
            }

            .invoice-box table tr.information table td {
                width: 100%;
                display: block;
                text-align: center;
            }
        }

        /** RTL **/
        .invoice-box.rtl {
            direction: rtl;
            font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        }

        .invoice-box.rtl table {
            text-align: right;
        }

        .invoice-box.rtl table tr td:nth-child(2) {
            text-align: left;
        }

    </style>
</head>

<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr>
                <td colspan="5" style="text-align: center">
                    <h1>LAPORAN TRANSAKSI</h1>
                    <h2>Electronic Shop <span style="color: rgb(21, 174, 221);"></span></h2>
                    <hr>
                </td>
            </tr>
            <tr class="top">
                <td colspan="5">
                    <table>
                        <tr>
                            <td>
                                Created: {{ date("d.m.Y H:i:s A", strtotime(now()))}}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr><td><b>Data Transaksi</td></tr>
            <tr class="heading">
                <th>No. Invoice</th>
                <th>Nama User</th>
                <th>Status Pembayaran</th>
                <th>Alamat</th>
                <th>Total Pembelian</th>
            </tr>

            @php
            $total= 0;
            @endphp

            @foreach($data as $item)
            <tr class="invoice" style="text-align: center">
                <td>
                    <span style="font-weight: bold;">#{{ $item->no_invoice }}</span>
                </td>
                <td>{{ $item->user->name }}</td>
                <td>{{ ($item->status == 1) ? 'Sudah Diverifikasi' : 'Belum Diverifikasi' }}</td>
                <td>{{ $item->alamat->alamat }}</td>
                <td>Rp. {{ number_format($item->total) }}</td>
            </tr>
            @php
            $total += $item->total;
            @endphp
            @endforeach

            <tr class="total heading" style="text-align: center">
                <td></td>
                <td></td>
                <td></td>
                <td style="font-weight: bold">TOTAL</td>
                <td style="font-weight: bold">{{ number_format($total, 0, ',', '.')}}</td>
            </tr>
        </table>
    </div>
</body>
</html>

resources/views/dashboard/admin/payment/create.blade.php
@extends('dashboard.main')

@section('title', 'Transaksi')


@section('content')
<div class="container mt-5">
 
    <div class="row justify-content-center align-items-center">
        <div class="card">
            <div class="card-header">
            Tambah Transaksi
        </div>
        <div class="card-body">
            @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            </div>
        @endif
        <form method="post" action="{{ route('kategori.store') }}" id="myForm" enctype="multipart/form-data">
        @csrf
            <div class="form-group">
                <label for="nama_kategori">Nama Kategori</label> 
                <input type="text" name="nama_kategori" class="form-control" id="nama_kategori" aria-describedby="Nim" > 
            </div>
            <br><br>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </div>
    </div>
 </div>
 </div>
@endsection

resources/views/dashboard/admin/payment/edit.blade.php
@extends('dashboard.main')

@section('title', 'Kategori')


@section('content')
<div class="container mt-5">
 
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Edit Kategori
        </div>
        <div class="card-body">
        @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form method="post" action="{{ route('kategori.update', $data_kategori_edit->id) }}" id="myForm" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="nama_kategori">Nama Kategori</label>
        <br> 
        <input type="text" name="nama_kategori" class="form-control" id="nama_kategori" value="{{ $data_kategori_edit->nama_kategori }}" aria-describedby="nama_kategori" > 
    </div>
    <br><br>
    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
    </div>
    </div>
</div>

@endsection

resources/views/dashboard/admin/payment/index.blade.php
@extends('dashboard.main')

@section('title', 'Transaksi')


@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2>Transaksi</h2>
    </div>
    <div class="float-right my-2 ">
        <a class="btn btn-success" href="{{ route('transaksi.create') }}"> Generate Laporan</a>
    </div>
    <table class="table table-bordered">
            <tr>
                <th>Nomor</th>
                <th>No. Invoice</th>
                <th>Nama User</th>
                <th>Total Pembelian</th>
                <th>Alamat</th>
                <th>Status Pembayaran</th>
                <th>Bukti Pembayaran</th>
                <th>Action</th>
            </tr>
            @foreach($data as $key => $item)
            <tr>
                <td>{{ $key+1 }}</td>
                <td>{{ $item->no_invoice }}</td>
                <td>{{ $item->user->name }}</td>
                <td>Rp. {{ number_format($item->total) }}</td>
                <td>{{ $item->alamat->alamat }}</td>
                <td>{{ ($item->status == 1) ? 'Sudah Diverifikasi' : 'Belum Diverifikasi' }}</td>
                <td><a class="btn btn-primary" href="{{ route('transaksi.show',$item->id) }}">Show Picture</a></td>
                <td>
                    @if($item->status == 0)
                    <a href="{{ route('transaksi.edit', $item->id) }}" class="btn btn-success">Verifikasi</a>
                    @endif
                </td>
                </td>
            </tr>
            @endforeach
    </table>

@endsection

resources/views/dashboard/admin/payment/show.blade.php
@extends('dashboard.main')

@section('title', 'Transaksi')


@section('content')
<div class="container mt-5">
 
    <div class="row justify-content-center align-items-center">
        <div class="card">
            <div class="card-header">
            Detail Transaksi
            </div>
            <div class="card-body">
                <img src="{{ asset('bukti/'. $data->bukti) }}" alt="" srcset="">
            </div><br>
            <a class="btn btn-success mt-3" href="{{ route('transaksi.index') }}">Kembali</a>
        </div>
    </div>
 </div>

@endsection